### PR TITLE
Configurable Prefix

### PR DESCRIPTION
**Pull request by IsAvaible**
Made the prefix that is added in front of the recognized text, configurable. Users may now set the prefix in Mod Menu.

Screenshot of the config UI
Screenshot in-game

### CODE REVIEW

**Comment by Jaffe2718** [comment]
You can add your name to the author list, and I will create a branch for you as `1.19.4-1.1.3`. Rremember to modify the mod version and add your own name to the author list.

**Comment by IsAvaible** [comment]
Thanks for the quick reply. I have implemented your suggested changes in my fork and would be ready to post a new pull request, once you create the branch.

**Comment by Jaffe2718** [comment]
No, I'll reupload 1.1.2-1.19.4, rename the branch and help you fill out the author list

**Comment by IsAvaible** [comment]
Appreciate it, thank you!

**Pull request merged**
